#!/bin/bash
fritzbox="fritz.box"
user="admin"
pass="xxx"
sidfile=/tmp/$fritzbox.sid

while true; do
    sleep 15

sidfile=/tmp/fritzbox.sid
if [[ ! -f $sidfile ]]
then 
	touch $sidfile
fi

sid=$(cat $sidfile)

result=$(curl -s "http://$fritzbox/login_sid.lua?sid=$sid" | grep -c "0000000000000000")

if [[ $result -gt 0 ]]
then

CHALLENGE=`wget --no-check-certificate -O - "http://$fritzbox/login_sid.lua" 2>/dev/null | sed 's/.*<Challenge>\(.*\)<\/Challenge>.*/\1/'`

CPSTR="$CHALLENGE-$pass"

MD5=`echo -n $CPSTR | iconv -f ISO8859-1 -t UTF-16LE | md5sum -b | awk '{print substr($0,1,32)}'`
RESPONSE="$CHALLENGE-$MD5"

URL_PARAMS="username=$user&response=$RESPONSE"

sid=`wget --no-check-certificate -O - "https://$fritzbox/login_sid.lua?$URL_PARAMS" 2>/dev/null | sed 's/.*<SID>\(.*\)<\/SID>.*/\1/'`
rm $sidfile
touch $sidfile

echo $sid
echo $sid >> $sidfile 
fi
sid=$(cat $sidfile)


echo "DOCSIS-Infos holen und in Variable ablegen"
docsis=$(curl -s "http://$fritzbox/data.lua" -d "xhr=1&sid=$sid&lang=de&page=docInfo&xhrId=all&no_sidrenew")

echo $docsis > /tmp/modem_raw.txt
 
echo "Globale Daten holen"
energy=$(curl -s "http://$fritzbox/data.lua" -d "xhr=1&sid=$sid&lang=de&page=ecoStat&xhrId=all&no_sidrenew")


echo "Ausgabedatei anlegen"
if [ -f "/tmp/modem.txt" ]; then rm /tmp/modem.txt
fi
touch /tmp/modem.txt


echo "Anzahl Upstream-Kanäle ermitteln"
kanaeleup=$(/bin/echo ${docsis} | /usr/bin/jq ".data.channelUs.docsis30[].powerLevel" | wc -l)

echo "Anzahl Upstream-Kanäle 3.1 ermitteln"
kanaeleup31=$(/bin/echo ${docsis} | /usr/bin/jq ".data.channelUs.docsis31[].powerLevel" | wc -l)

echo "Anzahl Downstream-Kanäle ermitteln"
kanaeledown=$(/bin/echo ${docsis} | /usr/bin/jq ".data.channelDs.docsis30[].powerLevel" | wc -l)

echo "Anzahl Downstream-Kanäle 3.1 ermitteln"
kanaeledown31=$(/bin/echo ${docsis} | /usr/bin/jq ".data.channelDs.docsis31[].powerLevel" | wc -l)

echo $kanaeleup $kanaeleup31 $kanaeledown $kanaeledown31
echo "channels sumup=$kanaeleup,sumup31=$kanaeleup31,sumdown=$kanaeledown,sumdown31=$kanaeledown31" >> /tmp/modem.txt

echo "Upstream DOCSIS 3.1 ermitteln"

for (( channel=0; channel<=$kanaeleup31-1; channel++ )) 
	do 	
		ChannelID[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis31[$channel].channelID")
		Powerlevel[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis31[$channel].powerLevel")
		Type[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis31[$channel].type")
		Freq[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis31[$channel].frequency")

		Freq=$(echo $Freq | tr -d ' ')
			
	echo "Upstream,USChannelID=$ChannelID,DOCSIS=3.1,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel"
	echo "Upstream,USChannelID=$ChannelID,DOCSIS=3.1,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel" >> /tmp/modem.txt
done


echo "Upstreamwerte ermitteln"

for (( channel=0; channel<=$kanaeleup-1; channel++ )) 
	do 	
		ChannelID[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis30[$channel].channelID")
		Freq[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis30[$channel].frequency")
		Type[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis30[$channel].type")
		Powerlevel[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelUs.docsis30[$channel].powerLevel")

 	echo "Upstream,USChannelID=$ChannelID,DOCSIS=3.0,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel"
	echo "Upstream,USChannelID=$ChannelID,DOCSIS=3.0,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel" >> /tmp/modem.txt
done

echo "Downstreamwerte ermitteln"

for (( channel=0; channel<=$kanaeledown-1; channel++ )) 
	do 	
		ChannelID[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis30[$channel].channelID")
		Freq[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis30[$channel].frequency")
		Type[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis30[$channel].type")
		Powerlevel[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis30[$channel].powerLevel") 

		mse[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis30[$channel].mse")
		nonCorrErrors[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis30[$channel].nonCorrErrors")
		corrErrors[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis30[$channel].corrErrors") 

	echo "Downstream,DSChannelID=$ChannelID,DOCSIS=3.0,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel,corrErrors=$corrErrors,nonCorrErrors=$nonCorrErrors,mse=$mse"
	echo "Downstream,DSChannelID=$ChannelID,DOCSIS=3.0,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel,corrErrors=$corrErrors,nonCorrErrors=$nonCorrErrors,mse=$mse" >> /tmp/modem.txt
done

echo "Downstreamwerte 3.1 ermitteln"

for (( channel=0; channel<=$kanaeledown31-1; channel++ )) 
	do 	
		ChannelID[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis31[$channel].channelID")
		Powerlevel[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis31[$channel].powerLevel")
		Type[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis31[$channel].type")
		Freq[$c]=$(/bin/echo ${docsis} | /usr/bin/jq -r ".data.channelDs.docsis31[$channel].frequency")

		Freq=$(echo $Freq | tr -d ' ')
			
	echo "Downstream,DSChannelID=$ChannelID,DOCSIS=3.1,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel"
	echo "Downstream,DSChannelID=$ChannelID,DOCSIS=3.1,Type=$Type,Freq=$Freq Powerlevel=$Powerlevel" >> /tmp/modem.txt
done


echo "Fritz!Box Stats ermitteln"
fritzbox_cable_cpuusage=$(/bin/echo ${energy} | /usr/bin/jq -r '.data.cpuutil.series[0] | last')
fritzbox_cable_cputemp=$(/bin/echo ${energy} | /usr/bin/jq -r '.data.cputemp.series[0] | last')
fritzbox_cable_ramfree=$(/bin/echo ${energy} | /usr/bin/jq -r '.data.ramusage.series[2] | last')

echo "FritzBox CPUusage=$fritzbox_cable_cpuusage,CPUtemp=$fritzbox_cable_cputemp,RAMfree=$fritzbox_cable_ramfree"
echo "FritzBox CPUusage=$fritzbox_cable_cpuusage,CPUtemp=$fritzbox_cable_cputemp,RAMfree=$fritzbox_cable_ramfree" >> /tmp/modem.txt

echo $energy >> /tmp/fb.txt

echo "Werte in die Influx laden"
curl -i -XPOST "https://maulberry:8086/write?db=DOCSIS&u=admin&p=xxx" --insecure --data-binary @/tmp/modem.txt

done

