{
 "title": "Modemwerte",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "USChannelID",
    "query": "SHOW TAG VALUES WITH KEY = \"USChannelID\""
   },
   {
    "name": "DSChannelID",
    "query": "SHOW TAG VALUES WITH KEY = \"DSChannelID\""
   },
   {
    "name": "Frequence",
    "query": "SHOW TAG VALUES WITH KEY = \"Freq\""
   }
  ]
 },
 "panels": [
  {
   "title": "Fritz!Box CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "select": [
      [
       { "params": [ "CPUtemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fritz!Box CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "select": [
      [
       { "params": [ "CPUusage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Upstreams",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channels",
     "select": [
      [
       { "params": [ "sumup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Downstreams",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channels",
     "select": [
      [
       { "params": [ "sumdown" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Downstreams 3.1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channels",
     "select": [
      [
       { "params": [ "sumdown31" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fritz!Box RAMfree",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "RAMfree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "select": [
      [
       { "params": [ "RAMfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_USChannelID $tag_Freq Mhz $tag_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "USChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Upstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "USChannelID", "operator": "=~", "value": "/^$USChannelID$/" }
     ]
    }
   ]
  },
  { "title": "Downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Downstream Power 3.1 4K",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Freq Mhz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.1" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "4K" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Power 64QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "!=", "value": "256QAM" },
      { "condition": "AND", "key": "Type", "operator": "!=", "value": "4K" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Power 256QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream MSE 64QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "mse" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "64QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream MSE 256QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "mse" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream corrErrors 64QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "64QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream corrErrors 265AQM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream noncorrErrors Alle",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "nonCorrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" }
     ]
    }
   ]
  }
 ]
}