{
 "title": "Modemwerte",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "USChannelID",
    "query": "SHOW TAG VALUES WITH KEY = \"USChannelID\""
   },
   {
    "name": "DSChannelID",
    "query": "SHOW TAG VALUES WITH KEY = \"DSChannelID\""
   },
   {
    "name": "Frequence",
    "query": "SHOW TAG VALUES WITH KEY = \"Freq\""
   },
   {
    "name": "MedFreq",
    "query": "SHOW TAG VALUES WITH KEY = \"Freq\" "
   },
   {
    "name": "LowFreq",
    "query": "SHOW TAG VALUES WITH KEY = \"Freq\" "
   },
   {
    "name": "HighFreq",
    "query": "SHOW TAG VALUES WITH KEY = \"Freq\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Fritz!Box CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "select": [
      [
       { "params": [ "CPUtemp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fritz!Box CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "select": [
      [
       { "params": [ "CPUusage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Upstreams",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channels",
     "select": [
      [
       { "params": [ "sumup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Downstreams",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channels",
     "select": [
      [
       { "params": [ "sumdown" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Downstreams 3.1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channels",
     "select": [
      [
       { "params": [ "sumdown31" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Upstreams 3.1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channels",
     "select": [
      [
       { "params": [ "sumup31" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fritz!Box RAMfree",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "RAMfree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FritzBox",
     "select": [
      [
       { "params": [ "RAMfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DOCSIS 3.1 Upstream",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_USChannelID $tag_Freq Mhz $tag_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "USChannelID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Upstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "DOCSIS", "operator": "=", "value": "3.1" },
      { "condition": "AND", "key": "USChannelID", "operator": "=~", "value": "/^$USChannelID$/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_USChannelID $tag_Freq Mhz $tag_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "USChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Upstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "USChannelID", "operator": "=~", "value": "/^$USChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Power 64QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_USChannelID $tag_Freq Mhz $tag_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "USChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Upstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "USChannelID", "operator": "=~", "value": "/^$USChannelID$/" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "64QAM" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Power 16QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_USChannelID $tag_Freq Mhz $tag_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "USChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Upstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "USChannelID", "operator": "=~", "value": "/^$USChannelID$/" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "16QAM" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Power 4QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_USChannelID $tag_Freq Mhz $tag_Type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "USChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Upstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "USChannelID", "operator": "=~", "value": "/^$USChannelID$/" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "4QAM" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" }
     ]
    }
   ]
  },
  { "title": "Downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Downstream Power 3.1 4K",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Freq Mhz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.1" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "4K" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Power 256QAM Low",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" },
      { "condition": "AND", "key": "Freq", "operator": "=~", "value": "/^$LowFreq$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Power 256QAM Med",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Freq", "operator": "=~", "value": "/^$MedFreq$/" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Power 64QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "Powerlevel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "!=", "value": "256QAM" },
      { "condition": "AND", "key": "Type", "operator": "!=", "value": "4K" }
     ]
    }
   ]
  },
  {
   "title": "Downstream MSE 256QAM Low",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "query": "SELECT last(\"mse\") FROM \"Downstream\" WHERE (\"DSChannelID\" =~ /^$DSChannelID$/ AND \"DOCSIS\" = '3.0' AND \"Type\" = '256QAM')  AND $timeFilter GROUP BY time($__interval), \"DSChannelID\", \"Freq\", \"Type\" fill(none)",
     "select": [
      [
       { "params": [ "mse" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" },
      { "condition": "AND", "key": "Freq", "operator": "=~", "value": "/^$LowFreq$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream MSE 256QAM Med",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "query": "SELECT last(\"mse\") FROM \"Downstream\" WHERE (\"DSChannelID\" =~ /^$DSChannelID$/ AND \"DOCSIS\" = '3.0' AND \"Type\" = '256QAM')  AND $timeFilter GROUP BY time($__interval), \"DSChannelID\", \"Freq\", \"Type\" fill(none)",
     "select": [
      [
       { "params": [ "mse" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" },
      { "condition": "AND", "key": "Freq", "operator": "=~", "value": "/^$MedFreq$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream MSE 64QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "mse" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "64QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream corrErrors 265AQM Low",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" },
      { "condition": "AND", "key": "Freq", "operator": "=~", "value": "/^$LowFreq$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream corrErrors 265AQM Med",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "256QAM" },
      { "condition": "AND", "key": "Freq", "operator": "=~", "value": "/^$MedFreq$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream corrErrors 64QAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" },
      { "condition": "AND", "key": "Type", "operator": "=", "value": "64QAM" }
     ]
    }
   ]
  },
  {
   "title": "Downstream noncorrErrors Alle",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_DSChannelID $tag_Type $tag_Freq Mhz ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DSChannelID" ], "type": "tag" },
      { "params": [ "Freq" ], "type": "tag" },
      { "params": [ "Type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Downstream",
     "select": [
      [
       { "params": [ "nonCorrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "DSChannelID", "operator": "=~", "value": "/^$DSChannelID$/" },
      { "condition": "AND", "key": "DOCSIS", "operator": "=", "value": "3.0" }
     ]
    }
   ]
  }
 ]
}